In [2]:
import torch

In [10]:
t1= torch.tensor(4.)
t1

torch.int64

In [11]:
## Vector Tensor
t2 =  torch.tensor([2., 3, 5, 7])
print(t2.dtype)

t2 =  torch.tensor([2, 3, 5, 7])
print(t2.dtype)   ##All the variables of tensor have same dtype

torch.float32
torch.int64


In [6]:
##Matrix Tensor
t3 = torch.tensor ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
## 3D Array
t4 = torch.tensor([   [[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]],
                     
                      [[1, 3, 5],
                      [2, 4, 6],
                      [3, 6, 9]]   ])
t4

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 3, 5],
         [2, 4, 6],
         [3, 6, 9]]])

In [12]:
print(t1)
t1.shape

tensor(4)


torch.Size([])

In [13]:
print(t2)
t2.shape

tensor([2, 3, 5, 7])


torch.Size([4])

In [14]:
print(t3)
t3.shape

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


torch.Size([3, 3])

In [15]:
print(t4)
t4.shape

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 3, 5],
         [2, 4, 6],
         [3, 6, 9]]])


torch.Size([2, 3, 3])