In [1]:
import torch
import numpy as np

In [2]:
#yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
#yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.7841,  3.6556, -2.0285],
        [-0.2582, -0.0197, -0.2728]], requires_grad=True)
tensor([-0.5761,  0.1687], requires_grad=True)


In [6]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [7]:
inputs @ w.t() + b

tensor([[214.3670, -31.7290],
        [262.6512, -42.5182],
        [439.8432, -40.7528],
        [161.5434, -37.1098],
        [262.4742, -38.6306]], grad_fn=<AddBackward0>)

In [8]:
#Our model is simply a function that performs a matrix multiplication of the inputs and the weights w (transposed) 
#and adds the bias b (replicated for each observation).
def model(x):
    return x @ w.t() + b

In [9]:
#Sending Inputs to model and storing in predictions
preds = model(inputs)
print(preds)

tensor([[214.3670, -31.7290],
        [262.6512, -42.5182],
        [439.8432, -40.7528],
        [161.5434, -37.1098],
        [262.4742, -38.6306]], grad_fn=<AddBackward0>)


In [ ]:
#Comparing with targets
print(targets)